global:
  scrape_interval: 15s
  external_labels:
    monitor: 'lambda-monitor'

scrape_configs:

  - job_name: "zookeeper"
    static_configs:
      - targets:
          - "zoo1:1234"
          - "zoo2:1234"
          - "zoo3:1234"
        labels:
          env: "dev"
    relabel_configs:
      - source_labels: [__address__]
        target_label: hostname
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'

  - job_name: "kafka-broker"
    static_configs:
      - targets:
          - "kafka1:1234"
          - "kafka2:1234"
          - "kafka3:1234"
        labels:
          env: "dev"
    relabel_configs:
      - source_labels: [__address__]
        target_label: hostname
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'

  - job_name: "schema-registry"
    static_configs:
      - targets:
          - "kafka-schema-registry:1234"
        labels:
          env: "dev"
    relabel_configs:
      - source_labels: [__address__]
        target_label: hostname
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'

  - job_name: "rest-proxy"
    static_configs:
      - targets:
          - "kafka-rest-proxy:1234"
        labels:
          env: "dev"
    relabel_configs:
      - source_labels: [__address__]
        target_label: hostname
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'